---
- name: Capture OS info
  hosts: all
  tasks:
    - name: Capture OS name
      debug:
        msg: "{{item}}"
      with_items:
        - "{{ansible_distribution}}"
        - "{{ansible_distribution_version}}"
        - "{{ansible_distribution_major_version}}"

