---
- name: Install tree on ubuntu servers
  hosts: ubuntu
  tasks:
    - name: Install using apt
      apt:
        name: tree
        state: present
        update_cache: yes
- name: Install tree on rhel servers
  hosts: rhel
  tasks:
    - name: Install using yum
      yum:
        name: tree
        state: present
        update_cache: yes
...
