---
- name: Install firewall using host scope variables
  hosts: webserver
  tasks:
    - name: Install firewall
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"

