---
- name: Create user on all servers
  hosts: dbserver 
  tasks:
    - name: Create user
      user:
        name: Anusha
        password: intelliqit
        home: /tmp/Anusha
        uid: 2222
        shell: /bin/bash
        comment: "A normal user"

...
